export const TOKEN_TO_CG_ID = {
  DPX: "dopex",
  RDPX: "dopex-rebate-token",
  GOHM: "governance-ohm",
  ETH: "ethereum",
  GMX: "gmx",
  BNB: "binancecoin",
  AVAX: "avalanche-2",
  METIS: "metis",
};

export const BLOCKCHAIN_TO_CHAIN_ID = {
  ETHEREUM: 1,
  ARBITRUM: 42161,
  BINANCE: 56,
  AVAX: 43114,
  METIS: 1088,
};

export const SSOVS = [
  {
    type: "call",
    name: "DPX",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "call",
    name: "RDPX",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "call",
    name: "ETH",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "call",
    name: "GOHM",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "call",
    name: "GMX",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "call",
    name: "AVAX",
    chainId: 43114,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "call",
    name: "BNB",
    chainId: 56,
    underlyingDecimals: 8,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "RDPX",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "ETH",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "GOHM",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "GMX",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "BTC",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "CRV",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "DPX",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
  {
    type: "put",
    name: "LUNA",
    chainId: 42161,
    underlyingDecimals: 18,
    totalEpochDeposits: 0,
    apy: 0,
    tvl: 0,
    currentEpoch: 0,
  },
];
