sources:
  - name: straddles
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psytama/dopex-straddles
    transforms:
      - autoPagination:
          validateSchema: true
  - name: straddles_polygon
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psytama/dopex-straddles-polygon
    transforms:
      - prefix:
          value: straddles_polygon
          includeRootOperations: true
      - autoPagination:
          validateSchema: true
  - name: ssov
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psytama/dopex-ssov
    transforms:
      - autoPagination:
          validateSchema: true
documents:
  - ./graphql/**/*.graphql
