export default [
  {
    symbol: "DPX",
    name: "Dopex Governance Token",
    cgId: "dopex",
    oracleAddress: "0xc373B9DB0707fD451Bc56bA5E9b029ba26629DF0",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
  {
    symbol: "rDPX",
    name: "Dopex Rebate Token",
    cgId: "dopex-rebate-token",
    oracleAddress: "0xe871E9BD0ccc595A626f5e1657c216cE457CEa43",
    oracleFunctionName: "getValue(string)",
    oracleFunctionArgs: ["RDPX/USD"],
    oracleFunction: "function getValue(string) view returns (uint128)",
    oracleGetter: "",
    decimals: 8,
    oracleType: "dia",
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    cgId: "ethereum",
    oracleAddress: "0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
  {
    symbol: "CRV",
    name: "Curve DAO Token",
    cgId: "curve-dao-token",
    oracleAddress: "0xaebDA2c976cfd1eE1977Eac079B4382acb849325",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
  {
    symbol: "GMX",
    name: "GMX",
    cgId: "gmx",
    oracleAddress: "0x60E07B25Ba79bf8D40831cdbDA60CF49571c7Ee0",
    oracleFunctionName: "getPriceInUSD()",
    oracleFunction: "function getPriceInUSD() view returns (uint256 price)",
    decimals: 8,
    oracleType: "custom",
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    cgId: "bitcoin",
    oracleAddress: "0x6ce185860a4963106506C203335A2910413708e9",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
  {
    symbol: "CVX",
    name: "Convex",
    cgId: "convex-finance",
    oracleAddress: "0x851175a919f36c8e30197c09a9a49da932c2cc00",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
  {
    symbol: "ARB",
    name: "Arbitrum",
    cgId: "arbitrum",
    oracleAddress: "0xb2a824043730fe05f3da2efafa1cbbe83fa548d6",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
  {
    symbol: "stETH",
    name: "Lido Staked Ether",
    cgId: "staked-ether",
    oracleAddress: "0x07c5b924399cc23c24a95c8743de4006a32b7f2a",
    oracleFunctionName: "latestRoundData()",
    oracleFunction:
      "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)",
    oracleGetter: "answer",
    decimals: 8,
    oracleType: "chainlink",
  },
];
