export const SSOVS = [
    {
        type: 'call',
        name: 'DPX',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'call',
        name: 'RDPX',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'call',
        name: 'ETH',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'call',
        name: 'GOHM',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'call',
        name: 'GMX',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'call',
        name: 'AVAX',
        chainId: 43114,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'call',
        name: 'BNB',
        chainId: 56,
        underlyingDecimals: 8,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'RDPX',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'ETH',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'GOHM',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'GMX',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'BTC',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'CRV',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'DPX',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
    {
        type: 'put',
        name: 'LUNA',
        chainId: 42161,
        underlyingDecimals: 18,
        totalEpochDeposits: 0,
        apy: 0,
        tvl: 0,
        currentEpoch: 0,
    },
]
